### ISSUE TITLE
Await backup success on migration

### ISSUE THREAD

**Issue by SilasPeters** [svsticky/constipated-koala#1115]
Koala's main task makes a backup of the database before migrating the database. However, the ansible script currently just ensures the task has started, and then immediatly starts migrating. We should both ensure that the backup was _successful_ and await the backups' completion.

In order to achieve this, the systemd service must use an exit code, which it probably already uses but I wanted to type it here.

Problemetic code: [`roles/koala/tasks/main.yml`]

```yml
      - name: "make pre-upgrade database backup to S3"
        become_user: "root"
        become: true
        ansible.builtin.systemd:
          name: "backup-postgres.service"
          state: "started"

      - name: "check whether the database exists"
        ansible.builtin.shell: nix-shell --run 'dotenv rails db:version'
        args:
          chdir: "/var/www/koala.{{ canonical_hostname }}"
          executable: "/bin/bash"
        register: "koala_database_version"

      - name: "parse database version message"
        ansible.builtin.set_fact:
          database_exists: "{{ koala_database_version.stdout_lines[-1] != 'Current version: 0' }}"

      - name: "run database setup if database does not exist"
        ansible.builtin.shell: nix-shell --run 'dotenv rails db:setup'
        args:
          chdir: "/var/www/koala.{{ canonical_hostname }}"
          executable: "/bin/bash"
        when: "not database_exists"
```
