### ISSUE TITLE
Koala link tag is broken in confirmation email

### ISSUE THREAD

**Issue by SpookyBoy99** [svsticky/constipated-koala#1122]
### Expected behaviour
![image](https://github.com/user-attachments/assets/886361b4-bcc8-4905-92b7-78a2a583c148)

### Actual behavior

![image](https://github.com/user-attachments/assets/5755f45b-bc73-4f6c-be2c-fcfc43c158b4)

### Problematic translation entry:

`mailings.en.yml:32`:
```yml
[...]
        welcome: Welcome to Sticky!
        wrap_up: Curious about which activities we will soon organize? You can find more information in our member portal, %{koala_link_start} Koala%{link_end}, and you can enroll there too! In this member portal you can also edit your profile.
      changed_instructions:
[...]
```
